name: Symfony CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      # Utilisation de la dernière version stable de setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Checkout du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Copier le fichier .env.test.local si non existant
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      # Cache des dépendances Composer
      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Installation des dépendances
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Créer une base de données SQLite pour les tests
      - name: Create SQLite Database
        run: |
          mkdir -p var/data
          touch var/data/database.sqlite

      # Exécution des tests PHPUnit
      - name: Run PHPUnit tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/data/database.sqlite
        run: vendor/bin/phpunit
